//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noticiasAuto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoticiasDBEntities : DbContext
    {
        public NoticiasDBEntities()
            : base("name=NoticiasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Equipas> Equipas { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Pilotos> Pilotos { get; set; }
        public virtual DbSet<Utilizadores> Utilizadores { get; set; }
    }
}
