//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noticiasAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipas()
        {
            this.Pilotos = new HashSet<Pilotos>();
            this.Noticias = new HashSet<Noticias>();
        }
    
        public int IdEquipa { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataFundacao { get; set; }
        public string Logo { get; set; }
        public string Presidente { get; set; }
        public string Nacionalidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pilotos> Pilotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noticias> Noticias { get; set; }
    }
}
